### PR TITLE
Fix #29

### LINKED ISSUE #29: 1.0.2 NoMethodError: undefined method `scan' for nil:NilClass
Staring with version 1.0.2 I'm seeing the following error:

```
     NoMethodError:
       undefined method `scan' for nil:NilClass
     # ./.bundle/ruby/2.7.0/gems/xsv-1.0.2/lib/xsv/helpers.rb:108:in `parse_number_format'
     # ./.bundle/ruby/2.7.0/gems/xsv-1.0.2/lib/xsv/sheet_rows_handler.rb:104:in `format_cell'
     # ./.bundle/ruby/2.7.0/gems/xsv-1.0.2/lib/xsv/sheet_rows_handler.rb:60:in `end_element'
     # ./.bundle/ruby/2.7.0/gems/xsv-1.0.2/lib/xsv/sax_parser.rb:68:in `block in parse'
     # ./.bundle/ruby/2.7.0/gems/xsv-1.0.2/lib/xsv/sax_parser.rb:19:in `loop'
     # ./.bundle/ruby/2.7.0/gems/xsv-1.0.2/lib/xsv/sax_parser.rb:19:in `parse'
     # ./.bundle/ruby/2.7.0/gems/xsv-1.0.2/lib/xsv/sheet.rb:64:in `each_row'
```

I'm guessing this was introduced in c653bb86a019b5de9f00dab5c0261548ff9b457f

It seems the `format` passed to `parse_number_format` isn't always a string.

The document was generated by [caxlsx](https://github.com/caxlsx/caxlsx).

### PR DESCRIPTION
**Pull request by shkm**

### CODE REVIEW

**Comment by shkm** [comment]
Oops, I see you already fixed this. Away it goes!
